[package]
name = "cyber-std"
version = "0.1.0"
authors = ["Valery Litvin <litvintech@gmail.com>"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into modules of Cyber"
repository = "https://github.com/cybercongress/cw-cyber"
homepage = "https://cyb.ai"
license = ""
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0-beta", features = ["iterator"] }
schemars = "0.8.1"
cw721 = { version = "0.11" }
serde = { version = "1.0.125", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta" }


