[package]
name = "cyber-std"
version = "0.1.0"
authors = ["CyberHead"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into modules of Cyber"
repository = "https://github.com/cybercongress/cw-cyber"
homepage = "https://github.com/cybercongress/go-cyber"
license = "Apache-2.0"
readme = "README.md"


[dependencies]
cosmwasm-std = { version = "1.0.0-beta5", features = ["iterator"] }
schemars = "0.8.1"
cw721 = { version = "0.11.1" }
cid = { version = "0.8.0" }
serde = { version = "1.0.125", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta5" }


