[package]
name = "cyber-std-test"
version = "0.2.1"
authors = ["CyberHead"]
edition = "2018"
description = "Multitest (and other test helpers) support for Cyber-specific contracts"
repository = "https://github.com/cybercongress/cw-cyber"
homepage = "https://github.com/cybercongress/go-cyber"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
cyber-std = { version = "0.2.1", path = "../cyber-std" }
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8.1"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
cw-multi-test = { version = "0.13.2" }
cw-storage-plus = { version = "0.13.2" }
anyhow = { version = "1" }
thiserror = { version = "1.0.21" }
