[package]
name = "cyber-cosmwasm"
version = "0.7.0"
authors = ["Valery Litvin <litvintech@gmail.com>"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into custom modules of Cyber"
repository = "https://github.com/cybercongress/cyber-cosmwasm"
license = ""
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "0.11.1", features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.11.1" }
